# Generated by Django 3.0.8 on 2020-07-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('email', models.EmailField(default='', max_length=254)),
                ('fathers_name', models.CharField(default='', max_length=256)),
                ('school', models.CharField(default='', max_length=256)),
                ('lastclasspercent', models.CharField(default='', max_length=256)),
                ('From_where_you_came_to_know_about_us', models.CharField(max_length=20)),
            ],
        ),
    ]
